name: laweather
description: "Stay Informed, Stay Ahead."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flex_color_scheme: ^7.3.1
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  introduction_screen: ^3.1.14
  dots_indicator: ^2.1.2
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  country_code_picker: ^3.0.0
  intl: ^0.18.0
  toggle_switch: ^2.3.0
  curved_navigation_bar: ^1.0.3
  provider: ^6.1.2
  flutter_gemini: ^2.0.3
  dash_chat_2: ^0.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter_native_splash:
  color: "#F9FAFD"
  color_dark: "#191A1D"
  image: "assets/images/splash/splash_light_mode.png"
  image_dark: "assets/images/splash/splash_dark_mode.png"
  android: true
  ios: true
  web: false

  android_12:
    color: "#F9FAFD"
    color_dark: "#191A1D"
    image: "assets/images/splash/android_12_splash_light_mode.png"
    image_dark: "assets/images/splash/android_12_splash_dark_mode.png"
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/on_boarding/
    - assets/images/weather_conditions/
