name: laweather
description: "Stay Informed, Stay Ahead."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter_native_splash:
  color: "#F9FAFD"
  color_dark: "#191A1D"
  image: "assets/images/splash/splash_light_mode.png"
  image_dark: "assets/images/splash/splash_dark_mode.png"
  android: true
  ios: true
  web: false

  android_12:
    color: "#F9FAFD"
    color_dark: "#191A1D"
    image: "assets/images/splash/android_12_splash_light_mode.png"
    image_dark: "assets/images/splash/android_12_splash_dark_mode.png"
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
